### ISSUE TITLE
Clean up directory before checkout

### ISSUE THREAD

**Issue by dobos** [dobos/domino#10]
http://domino.vo.elte.hu/Student/Submission.aspx?assignmentID=9&id=5767

Kivétel: Complex.Domino.Git.GitException

Kivétel üzenete:
error: The following untracked working tree files would be overwritten by checkout:
	2016-17-2/fiznum2/1.feladat/main3.c
Please move or remove them before you switch branches.
Aborting
Command: git checkout a966180a7d0b2f6eda77185b1eb44b36d72b715d

Verem:
   at Complex.Domino.Git.GitWrapper.Dispose() in C:\Data\dobos\project\domino\src\Complex.Domino.Git\Git\GitWrapper.cs:line 91
   at Complex.Domino.Git.GitWrapper.Call(Git git, Arguments args) in C:\Data\dobos\project\domino\src\Complex.Domino.Git\Git\GitWrapper.cs:line 37
   at Complex.Domino.Git.Git.CheckOut(String branch, Boolean newBranch) in C:\Data\dobos\project\domino\src\Complex.Domino.Git\Git\Git.cs:line 265
   at Complex.Domino.Git.Git.CheckOut(String branch) in C:\Data\dobos\project\domino\src\Complex.Domino.Git\Git\Git.cs:line 253
   at Complex.Domino.Lib.GitHelper.CheckOutSubmission() in C:\Data\dobos\project\domino\src\Complex.Domino.Lib\Lib\GitHelper.cs:line 356
   at Complex.Domino.Web.SubmissionPage.UpdateForm() in C:\Data\dobos\project\domino\src\Complex.Domino.Web\SubmissionPage.cs:line 136
   at Complex.Domino.Web.Student.Submission.UpdateForm() in C:\Data\dobos\project\domino\src\Complex.Domino.Web\Student\Submission.aspx.cs:line 55
   at Complex.Domino.Web.EntityPage`1.OnLoad(EventArgs e) in C:\Data\dobos\project\domino\src\Complex.Domino.Lib\Web\EntityPage.cs:line 75
   at Complex.Domino.Web.SubmissionPage.OnLoad(EventArgs e) in C:\Data\dobos\project\domino\src\Complex.Domino.Web\SubmissionPage.cs:line 53
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

===============================================================
Domino

**Comment by dobos** [comment]
This happens when the source file is changed and saved to fix build errors.

**Comment by dobos** [comment]
Or even better, add page to confirm reset when checking out a different version of an already edited submission.
